name: Fetch AbuseIPDB Blacklist

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour
  workflow_dispatch:     # Allows manual triggering

jobs:
  fetch-blacklist:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Fetch blacklist from AbuseIPDB
        run: |
          curl -G https://api.abuseipdb.com/api/v2/blacklist \
            -d confidenceMinimum=90 \
            -d limit=10000 \
            -H "Key: ${{ secrets.ABUSEIPDB_API_KEY }}" \
            -H "Accept: text/plain" \
            -o blacklist.txt

      - name: Commit blacklist file
        run: |
          git config --global user.name "kgoode517"
          git config --global user.email "kgoode71@gmail.com"
          git add blacklist.txt
          git commit -m "Update blacklist.txt"
          git push
